version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DATABASE_URL: jdbc:postgresql://db:5432/healthcare_db?sslmode=disable
      DB_USER: postgres
      DB_PASS: password
      JWT_SECRET: YmFzZTY0c2VjcmV0a2V5Zm9yaGVhbHRoY2FyZWNoYXRib3RhcHAxMjM0NTY3ODkw
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - db


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8081/api
    depends_on:
      - backend

volumes:
  db_data:
