spring.application.name=HealthCare AI Assistant

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
healthcare.jwt.secret=${JWT_SECRET}
healthcare.jwt.expiration=86400000

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Upload limitations
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
# OpenAI Configuration (Groq API setup)
openai.api-url=https://api.groq.com/openai/v1/chat/completions
openai.model=llama-3.3-70b-versatile
openai.api-key=${GROQ_API_KEY}
