spring.application.name=HealthCare AI Assistant

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
healthcare.jwt.secret=9a6747b0e1181282ec2d815777174620a8d46299b9c9f456102be833ce86f461
healthcare.jwt.expiration=86400000

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Upload limitations
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
